name: config of answer generation for arena-hard-v0.1

bench_name: ru-arena-hard-v0.1  # or ru-arena-general

temperature: 0.0
max_tokens: 4096
num_choices: 1

# a list of model to generate answers
model_list:
  - T-lite-instruct-0.1
  - GigaChat-Max-02-12-24
  - GigaChat-02-12-24
  - GigaChat-Pro-02-12-24
  - yandexgpt-lite-02-12-24
  - yandexgpt-02-12-24
  - claude-3-5-sonnet-20241022
  - claude-3-5-haiku-20241022
  - Vikhr-Nemo-12B-Instruct-R-21-09-24
  - meta-llama-Llama-3.1-8B-Instruct
  - gpt-4o-mini-2024-07-18
  - gpt-4o-2024-11-20
  - gpt-4-turbo-2024-04-09
  - mistralai-Mistral-Nemo-Instruct-2407
  - saiga_nemo_12b
  - saiga_llama3_8b
  - saiga_gemma2_9b
  - gemma-2-9b-it
